version: 2

models:

# Unit test: g1_insta_DimAisles
  - name: g1_insta_DimAisles
    description: "Dim table for Instacart aisles data"  
    columns:
      - name: aisle_id
        description: "Unique identifier for each aisle"
        tests:
          - not_null
          - unique
          - not_negative:
              column_name: aisle_id

      - name: aisle
        description: "Aisle name"
        tests:
          - not_null

# Unit test: g1_insta_DimDepartments
  - name: g1_insta_DimDepartments
    description: "Dim table for Instacart departments data"   
    columns:
      - name: department_id   /* Primary Key */
        description: "Unique identifier for each department"
        tests:
          - not_null
          - unique
          - not_negative:
              column_name: department_id

      - name: department
        description: "Department name"
        tests:
          - not_null

# Unit test: g1_insta_DimProducts
  - name: g1_insta_DimProducts
    description: "Dim table for Instacart products data"
    columns:
      - name: product_id   /* Primary Key */
        description: "Unique identifier for each product"
        tests:
          - not_null
          - unique
          - not_negative:
              column_name: product_id
          
      - name: product_name
        description: "Name of the product" 
        tests:
          - not_null
        

# Unit test: g1_insta_DimUsers
  - name: g1_insta_DimUsers
    description: "Dim list of users extracted from orders table."
    columns:
      - name: user_id
        description: "Primary key for users."
        tests:
          - not_null
          - unique
          - not_negative:
              column_name: user_id


# Unit test: g1_insta_FactOrders
  - name: g1_insta_FactOrder
    description: "Fact orders data with user linkage and standardized types."
    columns:
      - name: order_id
        description: "Foreign key for orders."
        tests:
          - not_null
          - not_negative:
              column_name: order_id
          - relationships:
              to: ref('g1_stg_insta_order_products')
              field: order_id

      - name: user_id
        description: "Foreign key referencing g1_stg_insta_users.user_id."
        tests:
          - not_null
          - not_negative:
              column_name: user_id
          - relationships:
              to: ref('g1_stg_insta_users')
              field: user_id

      - name: order_number
        description: "Sequential order number per user."
        tests:
          - not_null
          - not_negative:
              column_name: order_number

      - name: order_dow
        description: "Day of week order was placed (0=Sunday ... 6=Saturday)."
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: order_hour_of_day
        description: "Hour of day order was placed (0–23)."
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

      - name: days_since_prior_order
        description: "Days since previous order; may contain null (NaN) for first orders."

      - name: aisle_id
        description: "Foreign key  for each aisle id"
        tests:
          - not_null
          - not_negative:
              column_name: aisle_id
          - relationships:
              to: ref('g1_stg_insta_aisles')
              field: aisle_id
      
      - name: department_id
        description: "Foreign key  for each department_id"
        tests:
          - not_null
          - not_negative:
              column_name: department_id
          - relationships:
              to: ref('g1_stg_insta_departments')
              field: department_id

      - name: product_id
        description: "Foreign key  for each product_id"
        tests:
          - not_null
          - not_negative:
              column_name: product_id
          - relationships:
              to: ref('g1_stg_insta_products')
              field: product_id