version: 2

sources:
  - name: raw
    schema: raw  
    tables:
      - name: raw___insta_aisles
      - name: raw___insta_departments
      - name: raw___insta_order_products_prior
      - name: raw___insta_order_products_train
      - name: raw___insta_orders
      - name: raw___insta_products

  - name: clean
    schema: clean 
    tables:
      - name: g1_stg_insta_products
      - name: g1_stg_insta_order_products
      - name: g1_stg_insta_aisles

  - name: mart
    schema: mart
    tables:
      - name: g1_insta_DimAisles
      - name: g1_insta_DimProducts
      - name: g1_dq_order_products_anomalies
      - name: g1_dq_order_products_summary