version: 2

sources:
  - name: raw
    schema: raw  
    tables:
      - name: raw___insta_aisles
      - name: raw___insta_departments
      - name: raw___insta_order_products_prior
      - name: raw___insta_order_products_train
      - name: raw___insta_orders
      - name: raw___insta_products

  - name: clean
    schema: clean 
    tables:
      - name: g1_stg_insta_aisles
      - name: g1_stg_insta_departments
      - name: g1_stg_insta_products
